openapi: 3.0.1
info:
  title: Vehicles
  description: API Definition of Vehicles
  version: 1.0.0
servers:
- url: http://localhost:8290/vehicles
paths:
  /motorcycles:
    get:
      responses:
        default:
          description: Default response
  /cars:
    get:
      responses:
        default:
          description: Default response
